name: ec2-creation
on: [push] # triggers
jobs: # like stages in jenkins
  terraform:
<<<<<<< HEAD
    runs-on: self-hosted #this is self hosted runner
=======
    runs-on: self-hosted
>>>>>>> ed28d4b201ab8f43da6d359d10d30a1f52dba0c1
    steps: # stages
      - name: checkout the code
        uses:  actions/checkout@v5

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run:  terraform init

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: run plan
        run: terraform plan

      - name: run apply
        run: terraform apply -auto-approve
          
      
      #- name: run destroy
       # run: terraform destroy -auto-approve
          
   

